### PR TITLE
Update the template with breaking changes in 0.6

### PR DESCRIPTION
**Pull request by ealmloff**

### CODE REVIEW

**Comment by ealmloff** [comment]
> Is this not being merged because there will be some later changes?

This is not merged because the template is not versioned so merging this PR would update the template the 0.5 version of the dioxus-cli uses

**Comment by Andrew15-5** [comment]
Isn't the current version already a 0.6? How would you then change the template used specifically in 0.6? Does it have to be merged after 0.6 is officially released?

**Comment by ealmloff** [comment]
> Does it have to be merged after 0.6 is officially released?
Yes, we currently don't have versioning set up for the template, so the main branch of the template is always used in the CLI. That is currently compatible with the stable release of Dioxus (0.5)

**Comment by DogeDark** [comment]
https://github.com/ealmloff/dioxus-template/pull/2 in progress

**Pull request closed without merging**
