### PR TITLE
{{platform}}

### PR DESCRIPTION
**Pull request by hem1t**
Dioxus.toml knows fullstack now
changed all platform to lowercase

### CODE REVIEW

**Comment by mrxiaozhuox** [comment]
does Dioxus CLI already to change to lowercase? because I think this will be check in `dx`?

**Comment by hem1t** [comment]
> does Dioxus CLI already to change to lowercase? because I think this will be check in `dx`?

This I thought is simpler, I thought about checking in `dx` but that would mean adding extra codes, so I thought it would be better to just change what exists and I don't think anyone is going to change basics part of this template.

The only thing I don't like about this is that `TUI` looks better than `tui` and also for others.

**Comment by hem1t** [comment]
> does Dioxus CLI already to change to lowercase? because I think this will be check in `dx`?

**Comment by mrxiaozhuox** [comment]
I will close this PR first.

**Pull request closed without merging**
