### PR TITLE
Remove the TUI platform

### LINKED ISSUE #3028: `dx new`, and selecting `tui` fails
**Problem**

image

Running `cargo run` shows this error:
```
❯ cargo run
    Updating crates.io index
error: failed to select a version for `dioxus`.
    ... required by package `practice-001 v0.1.0 (/Users/rgdpro/sources/github-cskth/practice-dioxus-cli/practice-001)`
versions that meet the requirements `^0.5.6` are: 0.5.6

the package `practice-001` depends on `dioxus`, with features: `tui` but `dioxus` does not have these features.
```

Running `dx serve` shows the same error

**Steps To Reproduce**
**see above**

**Expected behavior**
**see above**

**Screenshots**
**see above**

**Environment:**
- Dioxus cli version: 0.5.7

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
- [x] I'm new to rust

### PR DESCRIPTION
**Pull request by ealmloff**
TUI is no longer a platform dioxus supports. Closes https://github.com/DioxusLabs/dioxus/issues/3028

### CODE REVIEW

**Comment by xeruf** [comment]
@ealmloff @Andrew15-5 any reasoning behind that? For me that would have been a great USP of Dioxus .

**Comment by Andrew15-5** [comment]
I think 2 main reasons: TUI was broken, but can be fixed, there is little demand and not much use cases for it. Well, it's also much more limited visually.

**Comment by ealmloff** [comment]
> @ealmloff @Andrew15-5 any reasoning behind that? For me that would have been a great USP of Dioxus .

TUI and the old Blitz architecture were developed together. TUI didn't see much adoption and it is no longer useful as a testing ground for the Blitz architecture now that Blitz is using parts of servo like stylo. Dropping official support for blitz makes it easier to iterate on core libraries like `dioxus-core`, and hotreloading.

That said, I don't think it would be too difficult to revive `dioxus-tui` as a community maintained crate if anyone is interested in maintaining it. The latest version of dioxus-tui is here https://github.com/DioxusLabs/blitz/tree/legacy/packages/dioxus-tui

**Comment by JakkuSakura** [comment]
FYI, I've made dioxus-tui working with latest dioxus v0.7.1 https://github.com/JakkuSakura/dioxus-tui

**Comment by JakkuSakura** [comment]
Image
Want to advertise my overhual of dioxus-tui. It works perfect on MacOS with HiDPI support. Multiple modes
https://github.com/JakkuSakura/dioxus-tui

**Pull request merged**
