### PR TITLE
Fix duplicate log dependency

### LINKED ISSUE #5: Log package conflicts
@Demonthos  @jkelleyrtp  Just installed the latest dioxus-cli after the merge, but I get a conflict error because in the cargo.toml file I got two log packages. 

`Caused by:
  TOML parse error at line 29, column 1
     |
  29 | log = "0.4.19"
     | ^
  duplicate key 'log' in table 'dependencies'`

image

_Originally posted by @alearcy in https://github.com/DioxusLabs/dioxus-template/issues/3#issuecomment-1664600350_

### PR DESCRIPTION
**Pull request by ealmloff**
Fixes a duplicate log dependency in the template

Fixes #5

### CODE REVIEW

**Comment by Demonthos** [comment]
> I think you should also move these [dependencies](https://github.com/DioxusLabs/dioxus-template/pull/6/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R75) above the `[features]` section, otherwise it will throw another parsing when you have a Cargo.toml like this:
> 
> ```toml
> [dependencies]
> x = y
> 
> [features]
> blabla = ["car"]
> 
> log = "0.4.19"
> ```
> 
> cargo tries to parse the `log` dep as if it was a feature, when it's not

Thanks for letting me know, this should be fixed now

**Comment by marc2332** [comment]
I think this could be merged, right?

**Comment by marc2332** [comment]
Sorry for pinging @jkelleyrtp, but I think this one is important 😄 👀

**Comment by jkelleyrtp** [comment]
Yes @marc2332 - sorry all, busy on the admin side of things!

**Pull request merged**
